Application/recop-comex-web-app/recop-comex/blueprints/linkages/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, send_from_directory, request
from flask_login import current_user, logout_user, login_required
from blueprints.linkages.forms import *
from data_access.models import user_account, event_information, event_participation, proposal_tracker, user_information, event_attachment, event_photo, donation, referral, user_photo
from data_access.queries import user_views, linkage_views, event_views, donation_views
from extensions import db, bcrypt
from static.email import generate, send_email
from static.pdf import generate_pdf
from datetime import datetime

import os

linkages = Blueprint('linkages', __name__, template_folder="templates")

APP_ROOT = os.path.dirname(os.path.abspath(__file__))

@linkages.before_request
def before_request():

	if current_user.is_authenticated and not current_user.is_anonymous:
		if current_user.type == 1:
			return redirect(url_for('admin.index'))
		elif current_user.type == 2:
			return redirect(url_for('registered.index'))
		elif current_user.type == 4:
			return redirect(url_for('communities.index'))
		elif current_user.type == 5:
			return redirect(url_for('religious_admin.index'))
		user_account.logout()

@linkages.route('/linkages/index')
@login_required
def index():

	photo = user_photo.photo(current_user.info_id)

	return render_template('/linkages/index.html', photo=photo, active='home')

@linkages.route('/linkages/events/<status>/search_<search>.page_<page>', methods=['GET', 'POST'])
@login_required
def events(status, search, page):

	if status=='scheduled':
		value='S'
	elif status=='new':
		value='N'
	elif status=='pending':
		value='P'
	elif status=='cancelled':
		value='C'
	elif status=='declined':
		value='X'
	elif status=='finished':
		value='F'
	else:
		value=status

	events = event_views.linkages_events([value, search, page])
	letters = event_attachment.letter_attached()
	
	photo = user_photo.photo(current_user.info_id)

	form = AttachLetterForm()

	if form.validate_on_submit():

		attach_letter = form.attach_letter.data
		old, extension = os.path.splitext(attach_letter.filename)
		filename = str(form.event_id.data)+extension
		file_path = 'static/attachment/signed_letter/' + filename

		value = [None,form.event_id.data,file_path,3]

		event_attachment.add(value)
		attach_letter.save(file_path)

		flash('Letter successfully attached!', 'success')

		return redirect(url_for('linkages.events', status=status, page='1', search=' '))

	form_search = SearchForm()

	if form_search.validate_on_submit():

		return redirect(url_for('linkages.events', status=status, page='1', search=form_search.search.data))

	return render_template('/linkages/events/index.html', title="Events", form_search=form_search, form=form, events=events, status=status, letters=letters, now=datetime.now(), search=search, photo=photo, active='events')

@linkages.route('/linkages/events/calendar', methods=['GET', 'POST'])
@login_required
def events_calendar():

	photo = user_photo.photo(current_user.info_id)

	events = event_information.calendar()
	
	return render_template('/linkages/events/index-calendar.html', title="Events", events=events, photo=photo, active='events')
	
@linkages.route('/linkages/events/show/<id>')
@login_required
def event_show(id):

	event = event_views.show_info(id)
	participants = event_views.show_participants([id,' '])

	form=SearchForm()

	return render_template('/linkages/events/show.html', title= event.name.title() , event = event, participants=participants,form=form, active='events')

@linkages.route('/linkages/events/conduct/<id>')
@login_required
def event_conduct(id):

	event = event_views.show_info(id)

	return render_template('/linkages/events/conduct.html', title= event.name.title() ,event=event, active='events')

@linkages.route('/linkages/events/photos/<id>', methods=['GET', 'POST'])
@login_required
def event_photos(id):

	event = event_views.show_info(id)

	photos  = event_photo.show(id)

	form = CaptionForm()

	if form.validate_on_submit():

		value = [form.photo.data, form.caption.data]
		event_photo.caption(value)
		flash('Caption added to photo!', 'success')
		return redirect(url_for('linkages.event_photos', id=event.id))

	return render_template('/linkages/events/photos.html', title= event.name.title() ,event=event, photos=photos, form=form, active='events')

@linkages.route('/linkages/events/photos/add/<id>', methods=['GET', 'POST'])
@login_required
def add_photos(id):

	event = event_views.show_info(id)
	form = PhotoForm()

	print()
	if form.validate_on_submit():

		for file in form.photos.data:

			old, extension = os.path.splitext(file.filename)

			extension = extension.lower()
			
			if extension==".jpg" or extension==".jpeg" or extension==".png" or extension==".gif":
				continue
			else:
				flash('Invalid file detected!', 'error')
				return redirect(url_for('linkages.add_photos', id=id))

		path = 'static/photos/events/'+id

		if not os.path.isdir(path):
			os.mkdir(path)

		for file in form.photos.data:

			old, extension = os.path.splitext(file.filename)
			filepath = path + '/' + file.filename
			file.save(filepath)

			value = [None, id, filepath, None, 'Y']
			event_photo.add(value)

		flash('Photos successfully uploaded!', 'success')
		return redirect(url_for('linkages.event_photos', id=id))

	return render_template('/linkages/events/add_photos.html', title= event.name.title() ,event=event, form=form, active='events')

@linkages.route('/linkages/events/photos/delete/<id>_from_<event>', methods=['GET', 'POST'])
@login_required
def delete_photo(id, event):

	event_photo.delete(id)

	flash('Photo was deleted!', 'success')

	return redirect(url_for('linkages.event_photos', id=event))

@linkages.route('/linkages/events/finish/<id>')
@login_required
def event_finish(id):

	event_information.update_status(id, 'F')
	flash('Event was finished! Kindly submit activity photos to complete the report.','success')

	return redirect(url_for('linkages.events', status='all', search=' ', page='1'))

@linkages.route('/linkages/events/attendance/<id>.search_<search>', methods=['GET', 'POST'])
@login_required
def event_attendance(id, search):

	event = event_views.show_info(id)
	participants = event_views.show_participants([id,search])

	form=SearchForm()

	if form.validate_on_submit():

		return redirect(url_for('linkages.event_attendance', id=id, search=form.search.data))

	return render_template('/linkages/events/attendance.html', title= event.name.title() ,event=event,participants=participants,form=form, search=search, active='events')

@linkages.route('/linkages/events/attendance/<id>/<action>.user_<user>')
@login_required
def attendance_action(id, action, user):

	if action=='present':

		event_participation.update([id,user,'P'])
		flash('Participant was marked as present!', 'success')

	if action=='absent':

		event_participation.update([id,user,'A'])
		flash('Participant was marked as absent!', 'success')

	return redirect(url_for('linkages.event_attendance', id=id, search=' '))

@linkages.route('/linkages/events/evaluation/<id>.search_<search>', methods=['GET', 'POST'])
@login_required
def event_evaluation(id, search):

	event = event_views.show_info(id)
	participants = event_views.show_attended([id,search])

	form=SearchForm()
	evaluate = EvaluationForm()

	if form.validate_on_submit():

		return redirect(url_for('linkages.event_evaluation', id=id, search=form.search.data))

	if evaluate.validate_on_submit():

		print(evaluate.participant.data)
		event_participation.evaluate([event.id, evaluate.participant.data, evaluate.rating.data, evaluate.comment.data])
		
		flash('Rating successfully submitted!', 'success')
		return redirect(url_for('linkages.event_evaluation', id=id, search=search))


	return render_template('/linkages/events/evaluation.html', title= event.name.title() ,event=event,participants=participants,form=form, evaluate = evaluate, search=search, active='events')

@linkages.route('/linkages/events/create', methods=['GET', 'POST'])
@login_required
def events_create():

	form = ProposalForm()

	linkages = linkage_views.target_linkages()

	for item in linkages:

		if item.type==3:
			name = item.company_name
		else:
			name = item.address

		form.select_link.choices.extend([(item.id, name)])

	if form.validate_on_submit():

		det = user_information.linkage_info(current_user.info_id)

		if det.company_name=='San Sebastian College Recoletos de Cavite':
			event_type=1
		else:
			event_type=2

		value = [
		None,current_user.info_id,form.title.data,
		form.description.data,form.objective.data,form.budget.data,form.location.data,
		form.event_date.data,form.participant_no.data, form.min_age.data, form.max_age.data,
		form.thrust.data,event_type,'N'
		]

		event_information.add(value)

		event = event_information.last_added(current_user.id)

		if form.target_link.data:

			comm = form.target_link.data.split('|',-1)

			for participant in comm:

				if participant!='':
					value = [None, event.id, participant, 'Y']
					event_participation.add(value)

		budget_plan = form.budget_plan.data
		old, extension = os.path.splitext(budget_plan.filename)
		filename = str(event.id)+extension
		file_path = 'static/attachment/budget_plan/' + filename

		value = [None,event.id,file_path,1]

		event_attachment.add(value)
		budget_plan.save(file_path)

		programme = form.programme.data
		old, extension = os.path.splitext(programme.filename)
		filename = str(event.id)+extension
		file_path = 'static/attachment/programme/' + filename

		value = [None,event.id,file_path,2]

		event_attachment.add(value)
		programme.save(file_path)

		value = [None, event.id, 'N']
		proposal_tracker.add(value)

		flash('Event proposal submitted! Please wait for the approval.', 'success')

		return redirect(url_for('linkages.events', status='all', page='1', search=' '))

	return render_template('/linkages/events/create.html', form=form, active='events')

Application/recop-comex-web-app/recop-comex/blueprints/linkages/templates/linkages-base.html
<!DOCTYPE html>
<html>

    <head>
        {% if title %}
        <title>{{ title }} | Linkages</title>
        {% else %}
        <title>ReCOP-ComEx</title>
        {% endif %}

        <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <link rel="stylesheet" type="text/css" href="../../../../static/css/bulma-0.7.2/css/bulma.css">
        <link rel="stylesheet" href="../../../../static/css/fontawesome-5.5.0/css/all.css">
        <link rel="stylesheet" href="../../../../static/css/recop-comex-style/css/style.css">
        <link rel="stylesheet" href="../../../../static/css/recop-comex-style/css/modal.css">
        <link rel="stylesheet" type="text/css" href="../../../../static/css/Bulma-extensions/bulma-checkradio/bulma-checkradio.min.css">
        <link rel="stylesheet" href="../../../../static/css/Bulma-extensions/bulma-carousel/bulma-carousel.min.css"> 
        <link rel="stylesheet" type="text/css" href="../../../../static/css/Bulma-extensions/bulma-tooltip/bulma-tooltip.min.css">
        <script type="text/javascript" src = "../../../../static/scripts/base.js" ></script>
          
    </head>

    <body> 
    
        <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="">
                    <img src="../../../../static/images/logo-menu.png">
                </a>

                <span class="navbar-burger burger" data-target="navMenu">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </span>
            </div>

            <div id="navMenu" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item {% if active=='home' %}is-active{% endif %}" href="{{url_for('linkages.index')}}">
                        <strong>Home</strong>
                    </a>
                    <a class="navbar-item {% if active=='events' %}is-active{% endif %}" href="{{url_for('linkages.events', status='all', page='1', search=' ')}}">
                        <strong>Events</strong>
                    </a>
                    <a class="navbar-item {% if active=='linkages' %}is-active{% endif %}" href="{{url_for('linkages.linkages_show', page='1', search=' ')}}">
                        <strong>Linkages</strong>
                    </a>
                    <a class="navbar-item {% if active=='communities' %}is-active{% endif %}" href="{{url_for('linkages.communities', page='1', search=' ')}}">
                        <strong>Communities</strong>
                    </a>
                    <a class="navbar-item {% if active=='donate' %}is-active{% endif %}" href="{{url_for('linkages.donate')}}">
                        <strong>Donate</strong>
                    </a>
                </div>

                <div class="navbar-end">
                    <a href="#" class="navbar-item">
                        <span class="icon is-small has-text-white">
                            <i class="nav-icons fas fa-question-circle "></i>
                        </span>
                    </a>
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">
                            <div>
                                {% if photo %}
                                <img class='nav-icons fa-2x' src='../../../{{photo.path}}'>
                                {% else %}
                                <i class="nav-icons fas fa-user-circle fa-2x"></i>
                                {% endif %}
                            </div>
                        </a>

                        <div class="navbar-dropdown is-right">
                            <a class="navbar-item" href="{{url_for('linkages.profile_about', user=current_user.username)}}">
                                My Profile
                            </a>
                            <a class="navbar-item" href="{{url_for('linkages.profile_settings_personal', user=current_user.username)}}">
                                Settings
                            </a>
                            <hr class="navbar-divider">
                            <a class="navbar-item" href="{{url_for('linkages.logout')}}">
                                Logout
                            </a>
                        </div>
                    </div>
                </div>
            </div>
		</nav>
		{% block content %} {% endblock %}
        <footer class="footer-distributed">

            <div class="footer-left">
                <figure class="footer-logo">
                    <img src="../../../static/images/logo-menu.png">

                 </figure>
                     
                
                <p class="footer-links">
                    <a href="{{url_for('linkages.index')}}">Home</a>
                    ·
                    <a href="#">About</a>
                    ·
                    <a href="{{url_for('linkages.termsandconditions')}}">Terms and Conditions</a>
                    ·
                    <a href="{{url_for('linkages.referral_users')}}">Referral</a>
                    ·
                    <a href="{{url_for('linkages.contactus')}}">Contact Us</a>
                </p>

                <p class="footer-company-name">ReCOP-ComEx &copy; 2019</p>
            </div>

            <div class="footer-center">

                <div> 
                    <i class="fa fa-map-marker-alt"></i>
                    <p><span>Manila- Cavite Road, Sta. Cruz, </span> Cavite Ciy, 4100 Philippines</p>
                </div>

                <div>
                    <i class="fa fa-phone"></i>
                    <p>434-1234</p>
                </div>

                <div>
                    <i class="fa fa-envelope"></i>
                    <p><a href="Recopcomex@yahoo.com">support@Recopcomex@yahoo.com</a></p>
                </div>

            </div>

            <div class="footer-right">

                <p class="footer-company-about">
                     <span>About the Re-COP</span>
                       The Recoletos de Cavite Community Outreach Program is the Institution's center for all community related activities 
                </p>

                <div class="footer-icons">

                    <a href="#"><i class="fab fa-facebook-square"></i></a>
                    <a href="#"><i class="fab fa-twitter-square"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                    <a href="#"><i class="fab fa-google-plus-square"></i></a>

                </div>

            </div>

        </footer>
	</body>
    
    <script type="text/javascript" src="../../../../static/css/Bulma-extensions/bulma-carousel/bulma-carousel.min.js"></script>
    <script type="text/javascript" src = "../../../../static/scripts/linkages.js" ></script>
    <script type = "text/javascript" src="../../../../static/scripts/sweetalert2.all.min.js"></script>       

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
             <script>
                Swal.fire({
                    title: "{{message}}", 
                    type: "{{category}}",
                    customClass: "modal",
                    buttonsStyling: false,
                    allowOutsideClick: false,
                    heightAuto: false,
                    confirmButtonClass: 'button is-medium submit'
                })
            </script>
            {% endfor %}
        {% endif %}
    {% endwith %} 

   
   

</html>